services:
  db:
    image: postgres:14-alpine
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  app:
    build:
      context: .
      target: development_build
    hostname: app
    stdin_open: true
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
     - "8000:8000"
  
  # ngrok:
  #   image: wernight/ngrok
  #   command: ngrok http django:8000
  #   ports:
  #     - "4040:4040"
  
volumes:
  pgdata: