# Generated by Django 5.0.6 on 2024-06-08 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_order_delete_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
