# Generated by Django 5.0.6 on 2024-06-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_order_item_itemorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.CharField(blank=True, choices=[('01', 'Mesa 01'), ('02', 'Mesa 02'), ('03', 'Mesa 03'), ('04', 'Mesa 04'), ('05', 'Mesa 05'), ('06', 'Mesa 06'), ('07', 'Mesa 07'), ('08', 'Mesa 08'), ('09', 'Mesa 09'), ('10', 'Mesa 10'), ('11', 'Mesa 11'), ('12', 'Mesa 12'), ('13', 'Mesa 13'), ('14', 'Mesa 14'), ('15', 'Mesa 15'), ('16', 'Mesa 16'), ('17', 'Mesa 17'), ('18', 'Mesa 18')], max_length=2, null=True),
        ),
    ]
