# Generated by Django 5.0.6 on 2024-06-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_itemorder_options_alter_itemorder_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Disponibilidade'),
        ),
        migrations.AddField(
            model_name='order',
            name='cliente',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
    ]
