# Generated by Django 5.0.6 on 2024-06-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_cliente_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='account_closing_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário de encerramento da conta'),
        ),
    ]
