# Generated by Django 5.0.6 on 2024-06-10 03:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_account_closing_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=2, verbose_name='Númeração')),
                ('availability', models.BooleanField(default=True, verbose_name='Disponibilidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Ocupada'),
        ),
    ]
