# Generated by Django 5.0.6 on 2024-06-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_order_table_order__table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Opções', 'verbose_name_plural': 'Cardádio'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='_table',
        ),
        migrations.AddField(
            model_name='order',
            name='_table',
            field=models.ManyToManyField(blank=True, null=True, to='core.table', verbose_name='Mesa'),
        ),
    ]
