# Generated by Django 5.0.6 on 2024-06-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_item_options_remove_order__table_order__table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Opções', 'verbose_name_plural': 'Cardápio'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='availability',
        ),
    ]
