# Generated by Django 5.0.6 on 2024-06-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_item_options_remove_order_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='_table',
        ),
        migrations.RemoveField(
            model_name='order',
            name='account_closing_time',
        ),
    ]
